In [10]:
import numpy as x
a=x.array((10,20,30,40,50))
print(a,type(a))


[10 20 30 40 50] <class 'numpy.ndarray'>


In [11]:
import numpy as num
a=num.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as ap
b=ap.array([[1,2,3],[4,5,6]],dtype=float)
print(b)


[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
import numpy as num
num.empty((2,2))#they are the memory locations which are allocated by the interpreter

array([[0.00000000e+000, 8.40987008e-312],
       [8.40987009e-312, 8.40987009e-312]])

In [ ]:
import numpy as np
array_id = np.zeros(5)
print(a