In [2]:
import numpy as np
arr = np.arange(1, 21)
print("Array:", arr)
print("ndim:", arr.ndim)      
print("shape:", arr.shape)    
print("size:", arr.size)      
print("dtype:", arr.dtype)    

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
ndim: 1
shape: (20,)
size: 20
dtype: int64


In [3]:
import numpy as np
x = np.random.randint(0, 100, size=10)
print("Original array:", x)
sorted_copy = np.sort(x)
print("Sorted with np.sort():", sorted_copy)
print("After np.sort(), original still:", x)
x.sort()
print("After x.sort(), original is now:", x)

Original array: [30 26  9 88 57 57 99  6 33 46]
Sorted with np.sort(): [ 6  9 26 30 33 46 57 57 88 99]
After np.sort(), original still: [30 26  9 88 57 57 99  6 33 46]
After x.sort(), original is now: [ 6  9 26 30 33 46 57 57 88 99]


In [4]:
import numpy as np
np.random.seed(0)
arr = np.random.randint(0, 51, size=(4, 5))
print("Array:\n", arr)
print("Item size:", arr.itemsize)
print("Total bytes:", arr.nbytes)

Array:
 [[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
Item size: 4
Total bytes: 80


In [5]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("Array:\n", arr)
print("Element at row 2, col 3:", arr[1, 2])
print("Last row:", arr[-1])
print("Last column:", arr[:, -1])


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 2, col 3: 7
Last row: [ 9 10 11 12]
Last column: [ 4  8 12]


In [6]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print("Original Array:\n", arr)
subarray = arr[:2, :2]
print("\n(a) First 2 rows & 2 cols:\n", subarray)
alternate_cols = arr[:, ::2]
print("\n(b) Every alternate column:\n", alternate_cols)
reversed_cols = arr[:, ::-1]
print("\n(c) Columns reversed:\n", reversed_cols)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(a) First 2 rows & 2 cols:
 [[1 2]
 [5 6]]

(b) Every alternate column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]

(c) Columns reversed:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [1]:
import numpy as np

name = ['alice', 'bob', 'cathy', 'doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data = np.zeros(
    4,
    dtype={
        'names': ('name', 'age', 'weight'),
        'formats': ('U10', 'i4', 'f8')
    }
)

print("Structured array using a compound data type")
print(data.dtype)

data['name'] = name
data['age'] = age
data['weight'] = weight

print("Filled structured array")
print(data)

print("All names")
print(data['name'])

print("First row of data")
print(data[0])

print("Name from last row")
print(data[-1]['name'])

print("Names where age is under 30")
print(data[data['age'] < 30]['name'])


# Different ways to create a structured data type

print(np.dtype({
    'names': ('name', 'age', 'weight'),
    'formats': ('U10', 'i4', 'f8')
}))

print(np.dtype({
    'names': ('name', 'age', 'weight'),
    'formats': ((np.str_, 10), int, np.float32)
}))

print(np.dtype([
    ('name', 'S10'),
    ('age', 'i4'),
    ('weight', 'f8')
]))

print(np.dtype('S10,i4,f8'))


# Structured array with a 3x3 matrix
tp = np.dtype([
    ('id', 'i8'),
    ('mat', 'f8', (3, 3))
])

x = np.zeros(1, dtype=tp)

print(x[0])
print(x['mat'][0])

Structured array using a compound data type
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
Filled structured array
[('alice', 25, 55. ) ('bob', 45, 85.5) ('cathy', 37, 68. )
 ('doug', 19, 61.5)]
All names
['alice' 'bob' 'cathy' 'doug']
First row of data
('alice', 25, 55.0)
Name from last row
doug
Names where age is under 30
['alice' 'doug']
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('name', '<U10'), ('age', '<i8'), ('weight', '<f4')]
[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')]
[('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')]
(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
